nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-3.2.4.cjs

npmScopes:
  fortawesome:
    npmAlwaysAuth: true
    npmRegistryServer: "https://npm.fontawesome.com/"
    npmAuthToken: ${FONT_AWESOME_AUTH_TOKEN?}