approvedGitRepositories:
  - "https://github.com/bethinkpl/vue-popper.git"

compressionLevel: mixed

defaultSemverRangePrefix: ""

enableGlobalCache: false

enableScripts: false

nodeLinker: node-modules

npmMinimalAgeGate: "1w"

npmScopes:
  fortawesome:
    npmAlwaysAuth: true
    npmAuthToken: "${FONT_AWESOME_AUTH_TOKEN}"
    npmRegistryServer: "https://npm.fontawesome.com/"

supportedArchitectures:
  cpu:
    - arm64
    - x64
  libc:
    - glibc
  os:
    - darwin
    - linux

yarnPath: .yarn/releases/yarn-4.17.0.cjs
