import { config, dom, library } from '@fortawesome/fontawesome-svg-core';

import {
	faAddressCard,
	faAngleDown,
	faAngleLeft,
	faAngleRight,
	faAngleUp,
	faBoxArchive,
	faCircleArrowLeft,
	faCircleArrowRight,
	faArrowDownToLine,
	faBadgePercent,
	faBan,
	faBars,
	faBell,
	faBellSlash,
	faBook,
	faCalendarDays,
	faCircleExclamation,
	faSquareCaretRight,
	faChartBar,
	faChartLine,
	faCircleCheck,
	faSquareCheck,
	faCircle,
	faCircleNotch,
	faChevronDown,
	faChevronLeft,
	faChevronRight,
	faChevronUp,
	faClock,
	faCode,
	faGear,
	faComment,
	faCommentDots,
	faComments,
	faCompress,
	faEllipsis,
	faArrowsMaximize,
	faTriangleExclamation,
	faEye,
	faEyeSlash,
	faFileLines,
	faFileInvoiceDollar,
	faFilm,
	faFilter,
	faFlag,
	faFaceFrown,
	faGem,
	faGift,
	faEarthAmericas,
	faGraduationCap,
	faHandPointLeft,
	faHeartPulse,
	faClockRotateLeft,
	faHouse,
	faHourglassEnd,
	faHourglass,
	faHourglassStart,
	faCircleInfo,
	faKey,
	faKeyboard,
	faLightbulb,
	faLink,
	faList,
	faLockKeyhole,
	faWandMagic,
	faLocationDot,
	faMedal,
	faFaceMeh,
	faMinus,
	faMoneyBill1,
	faArrowPointer,
	faMusic,
	faPaperPlane,
	faPaperclip,
	faPencil,
	faPlay,
	faPlus,
	faCircleQuestion,
	faReply,
	faFloppyDisk,
	faMagnifyingGlass,
	faShare,
	faShieldBlank,
	faCartShopping,
	faArrowRightFromBracket,
	faSignal,
	faSitemap,
	faSliders,
	faFaceSmile,
	faSquare,
	faStar,
	faArrowsRotate,
	faGauge,
	faTag,
	faTags,
	faListCheck,
	faThumbsUp,
	faXmarkCircle,
	faTrashCan,
	faTrophyStar,
	faArrowRotateLeft,
	faLinkSlash,
	faUnlockKeyhole,
	faUpload,
	faUser,
	faWindowMaximize,
} from '@fortawesome/pro-regular-svg-icons';
import {
	faArrowDown as fasArrowDown,
	faArrowLeft as fasArrowLeft,
	faArrowRight as fasArrowRight,
	faArrowUp as fasArrowUp,
	faArrowsLeftRight as fasArrowsLeftRight,
	faBookmark as fasBookmark,
	faCamera as fasCamera,
	faCheck as fasCheck,
	faCircleCheck as fasCircleCheck,
	faGear as fasGear,
	faGears as fasGears,
	faComment as fasComment,
	faExclamation as fasExclamation,
	faFileLines as fasFileLines,
	faFolder as fasFolder,
	faHandSpock as fasHandSpock,
	faHeart as fasHeart,
	faInfo as fasInfo,
	faLightbulb as fasLightbulb,
	faCirclePlay as fasCirclePlay,
	faHands as fasHands,
	faSitemap as fasSitemap,
	faStar as fasStar,
	faStopwatch as fasStopwach,
	faThumbsUp as fasThumbsUp,
	faThumbtack as fasThumbtack,
	faVideo as fasVideo,
	faVolumeHigh as fasVolumeHigh,
} from '@fortawesome/pro-solid-svg-icons';

import {
	faChevronLeft as falChevronLeft,
	faChevronRight as falChevronRight,
	faXmark as falXmark,
} from '@fortawesome/pro-light-svg-icons';

import { faFacebook } from '@fortawesome/free-brands-svg-icons';

export const FONTAWESOME_ICONS = {
	FA_ADDRESS_CARD: faAddressCard,
	FA_ANGLE_DOWN: faAngleDown,
	FA_ANGLE_LEFT: faAngleLeft,
	FA_ANGLE_RIGHT: faAngleRight,
	FA_ANGLE_UP: faAngleUp,
	FA_ARCHIVE: faBoxArchive,
	FA_ARROWS_H_SOLID: fasArrowsLeftRight,
	FA_ARROW_CIRCLE_LEFT: faCircleArrowLeft,
	FA_ARROW_CIRCLE_RIGHT: faCircleArrowRight,
	FA_ARROW_DOWN_SOLID: fasArrowDown,
	FA_ARROW_LEFT_SOLID: fasArrowLeft,
	FA_ARROW_RIGHT_SOLID: fasArrowRight,
	FA_ARROW_UP_SOLID: fasArrowUp,
	FA_ARROW_TO_BOTTOM: faArrowDownToLine,
	FA_BADGE_PERCENT: faBadgePercent,
	FA_BAN: faBan,
	FA_BARS: faBars,
	FA_BELL: faBell,
	FA_BELL_SLASH: faBellSlash,
	FA_BOOK: faBook,
	FA_BOOKMARK_SOLID: fasBookmark,
	FA_CALENDAR_ALT: faCalendarDays,
	FA_CAMERA_ALT_SOLID: fasCamera,
	FA_CARET_SQUARE_RIGHT: faSquareCaretRight,
	FA_CHART_BAR: faChartBar,
	FA_CHART_LINE: faChartLine,
	FA_CHECK_SOLID: fasCheck,
	FA_CHECK_CIRCLE: faCircleCheck,
	FA_CHECK_CIRCLE_SOLID: fasCircleCheck,
	FA_CHECK_SQUARE: faSquareCheck,
	FA_CHEVRON_DOWN: faChevronDown,
	FA_CHEVRON_LEFT: faChevronLeft,
	FA_CHEVRON_LEFT_LIGHT: falChevronLeft,
	FA_CHEVRON_RIGHT: faChevronRight,
	FA_CHEVRON_RIGHT_LIGHT: falChevronRight,
	FA_CHEVRON_UP: faChevronUp,
	FA_CIRCLE: faCircle,
	FA_CIRCLE_NOTCH: faCircleNotch,
	FA_CLOCK: faClock,
	FA_CODE: faCode,
	FA_COG: faGear,
	FA_COGS_SOLID: fasGears,
	FA_COG_SOLID: fasGear,
	FA_COMMENT: faComment,
	FA_COMMENTS: faComments,
	FA_COMMENT_DOTS: faCommentDots,
	FA_COMMENT_SOLID: fasComment,
	FA_COMPRESS: faCompress,
	FA_ELLIPSIS_H: faEllipsis,
	FA_EXCLAMATION_SOLID: fasExclamation,
	FA_EXCLAMATION_CIRCLE: faCircleExclamation,
	FA_EXCLAMATION_TRIANGLE: faTriangleExclamation,
	FA_EXPAND_ARROWS: faArrowsMaximize,
	FA_EYE: faEye,
	FA_EYE_SLASH: faEyeSlash,
	FA_FACEBOOK: faFacebook,
	FA_FILE_ALT: faFileLines,
	FA_FILE_INVOICE_DOLLAR: faFileInvoiceDollar,
	FA_FILE_ALT_SOLID: fasFileLines,
	FA_FILM: faFilm,
	FA_FILTER: faFilter,
	FA_FLAG: faFlag,
	FA_FOLDER_SOLID: fasFolder,
	FA_FROWN: faFaceFrown,
	FA_GEM: faGem,
	FA_GIFT: faGift,
	FA_GLOBE: faEarthAmericas,
	FA_GRADUATION_CAP: faGraduationCap,
	FA_HAND_POINT_LEFT: faHandPointLeft,
	FA_HAND_SPOCK_SOLID: fasHandSpock,
	FA_HEARTBEAT: faHeartPulse,
	FA_HEART_SOLID: fasHeart,
	FA_HISTORY: faClockRotateLeft,
	FA_HOME: faHouse,
	FA_HOURGLASS_END: faHourglassEnd,
	FA_HOURGLASS_HALF: faHourglass,
	FA_HOURGLASS_START: faHourglassStart,
	FA_INFO_SOLID: fasInfo,
	FA_INFO_CIRCLE: faCircleInfo,
	FA_KEY: faKey,
	FA_KEYBOARD: faKeyboard,
	FA_LIGHTBULB: faLightbulb,
	FA_LIGHTBULB_SOLID: fasLightbulb,
	FA_LINK: faLink,
	FA_LIST: faList,
	FA_LOCK_ALT: faLockKeyhole,
	FA_MAGIC: faWandMagic,
	FA_MAP_MARKER_ALT: faLocationDot,
	FA_MEDAL: faMedal,
	FA_MEH: faFaceMeh,
	FA_MINUS: faMinus,
	FA_MONEY_BILL_ALT: faMoneyBill1,
	FA_MOUSE_POINTER: faArrowPointer,
	FA_MUSIC: faMusic,
	FA_PAPERCLIP: faPaperclip,
	FA_PAPER_PLANE: faPaperPlane,
	FA_PENCIL: faPencil,
	FA_PLAY: faPlay,
	FA_PLAY_CIRCLE_SOLID: fasCirclePlay,
	FA_PLUS: faPlus,
	FA_QUESTION_CIRCLE: faCircleQuestion,
	FA_REPLY: faReply,
	FA_SAVE: faFloppyDisk,
	FA_SEARCH: faMagnifyingGlass,
	FA_SHARE: faShare,
	FA_SHIELD_ALT: faShieldBlank,
	FA_SHOPPING_CART: faCartShopping,
	FA_SIGNAL: faSignal,
	FA_SIGN_LANGUAGE_SOLID: fasHands,
	FA_SIGN_OUT: faArrowRightFromBracket,
	FA_SITEMAP: faSitemap,
	FA_SITEMAP_SOLID: fasSitemap,
	FA_SLIDERS_H: faSliders,
	FA_SMILE: faFaceSmile,
	FA_SQUARE: faSquare,
	FA_STAR: faStar,
	FA_STAR_SOLID: fasStar,
	FA_STOPWATCH_SOLID: fasStopwach,
	FA_SYNC: faArrowsRotate,
	FA_TACHOMETER_ALT_FAST: faGauge,
	FA_TAG: faTag,
	FA_TAGS: faTags,
	FA_TASKS: faListCheck,
	FA_THUMBS_UP: faThumbsUp,
	FA_THUMBS_UP_SOLID: fasThumbsUp,
	FA_THUMBTACK_SOLID: fasThumbtack,
	FA_TIMES_CIRCLE: faXmarkCircle,
	FA_TIMES_LIGHT: falXmark,
	FA_TRASH_ALT: faTrashCan,
	FA_TROPHY_ALT: faTrophyStar,
	FA_UNDO: faArrowRotateLeft,
	FA_UNLINK: faLinkSlash,
	FA_UNLOCK_ALT: faUnlockKeyhole,
	FA_UPLOAD: faUpload,
	FA_USER: faUser,
	FA_VIDEO_SOLID: fasVideo,
	FA_VOLUME_UP_SOLID: fasVolumeHigh,
	FA_WINDOW_MAXIMIZE: faWindowMaximize,
} as const;

export function initialize() {
	library.add(...Object.values(FONTAWESOME_ICONS));
}

export function initializeWithDomWatcher() {
	initialize();

	config.autoReplaceSvg = 'nest';
	dom.watch();
}
