import { config, dom, library } from '@fortawesome/fontawesome-svg-core';

import {
	faAddressCard,
	faAngleDown,
	faAngleLeft,
	faAngleRight,
	faAngleUp,
	faArrowDownToLine,
	faArrowPointer,
	faArrowRightFromBracket,
	faArrowRotateLeft,
	faArrowsMaximize,
	faArrowsRotate,
	faBadgePercent,
	faBan,
	faBars,
	faBell,
	faBellSlash,
	faBook,
	faBoxArchive,
	faCalendarDays,
	faCartShopping,
	faChartColumn,
	faChartLineUp,
	faChevronDown,
	faChevronLeft,
	faChevronRight,
	faChevronUp,
	faCircle,
	faCircleArrowLeft,
	faCircleArrowRight,
	faCircleCheck,
	faCircleEllipsis,
	faCircleExclamation,
	faCircleInfo,
	faCircleNotch,
	faCircleQuestion,
	faCircleXmark,
	faClock,
	faClockRotateLeft,
	faCode,
	faComment,
	faCommentDots,
	faComments,
	faCompress,
	faEarthAmericas,
	faEllipsis,
	faEllipsisVertical,
	faEye,
	faEyeSlash,
	faFaceFrown,
	faFaceMeh,
	faFaceSmile,
	faFileInvoiceDollar,
	faFileLines,
	faFilm,
	faFilter,
	faFlag,
	faFloppyDisk,
	faGaugeHigh,
	faGear,
	faGem,
	faGift,
	faGraduationCap,
	faGrid,
	faHandPointLeft,
	faHeartPulse,
	faHourglass,
	faHourglassEnd,
	faHourglassStart,
	faHouse,
	faKey,
	faKeyboard,
	faLightbulb,
	faLink,
	faLinkSlash,
	faList,
	faListCheck,
	faListOl,
	faLocationDot,
	faLockKeyhole,
	faMagnifyingGlass,
	faMedal,
	faMemoCircleInfo,
	faMinus,
	faMoneyBill1,
	faMusic,
	faPaperPlane,
	faPaperclip,
	faPencil,
	faPenCircle,
	faPenField,
	faPlay,
	faPlus,
	faPrint,
	faReply,
	faShare,
	faShieldHalved,
	faSignal,
	faSitemap,
	faSliders,
	faSpellCheck,
	faSquare,
	faSquareCaretRight,
	faSquareCheck,
	faSquareList,
	faStar,
	faTag,
	faTags,
	faThumbsUp,
	faTrashCan,
	faTriangleExclamation,
	faTrophyStar,
	faUnlockKeyhole,
	faUpload,
	faUser,
	faWandMagicSparkles,
	faWindowMaximize,
	faXmark,
	faSpinnerThird,
} from '@fortawesome/pro-regular-svg-icons';
import {
	faArrowDown as fasArrowDown,
	faArrowLeft as fasArrowLeft,
	faArrowRight as fasArrowRight,
	faArrowUp as fasArrowUp,
	faArrowsLeftRight as fasArrowsLeftRight,
	faBookmark as fasBookmark,
	faBookSparkles as fasBookSparkles,
	faCamera as fasCamera,
	faCaretSquareRight as fasCaretSquareRight,
	faCheck as fasCheck,
	faCircleCheck as fasCircleCheck,
	faCirclePlay as fasCirclePlay,
	faComment as fasComment,
	faExclamation as fasExclamation,
	faFileLines as fasFileLines,
	faFilePen as fasFilePen,
	faFlask as fasFlask,
	faFolder as fasFolder,
	faGear as fasGear,
	faGears as fasGears,
	faHandSpock as fasHandSpock,
	faHands as fasHands,
	faHeart as fasHeart,
	faInfo as fasInfo,
	faLightbulb as fasLightbulb,
	faMemoCircleInfo as fasMemoCircleInfo,
	faMessageQuestion as fasMessageQuestion,
	faSitemap as fasSitemap,
	faStar as fasStar,
	faStopwatch as fasStopwach,
	faThumbsUp as fasThumbsUp,
	faThumbtack as fasThumbtack,
	faTriangleExclamation as fasTriangleExclamation,
	faVideo as fasVideo,
	faVolumeHigh as fasVolumeHigh,
} from '@fortawesome/pro-solid-svg-icons';

import {
	faChevronLeft as falChevronLeft,
	faChevronRight as falChevronRight,
} from '@fortawesome/pro-light-svg-icons';

import { faFacebook } from '@fortawesome/free-brands-svg-icons';

export const FONTAWESOME_ICONS = {
	FA_ADDRESS_CARD: faAddressCard,
	FA_ANGLE_DOWN: faAngleDown,
	FA_ANGLE_LEFT: faAngleLeft,
	FA_ANGLE_RIGHT: faAngleRight,
	FA_ANGLE_UP: faAngleUp,
	FA_ARROWS_LEFT_RIGHT_SOLID: fasArrowsLeftRight,
	FA_ARROWS_MAXIMIZE: faArrowsMaximize,
	FA_ARROWS_ROTATE: faArrowsRotate,
	FA_ARROW_DOWN_SOLID: fasArrowDown,
	FA_ARROW_DOWN_TO_LINE: faArrowDownToLine,
	FA_ARROW_LEFT_SOLID: fasArrowLeft,
	FA_ARROW_POINTER: faArrowPointer,
	FA_ARROW_RIGHT_FROM_BRACKET: faArrowRightFromBracket,
	FA_ARROW_RIGHT_SOLID: fasArrowRight,
	FA_ARROW_ROTATE_LEFT: faArrowRotateLeft,
	FA_ARROW_UP_SOLID: fasArrowUp,
	FA_BADGE_PERCENT: faBadgePercent,
	FA_BAN: faBan,
	FA_BARS: faBars,
	FA_BELL: faBell,
	FA_BELL_SLASH: faBellSlash,
	FA_BOOK: faBook,
	FA_BOOKMARK_SOLID: fasBookmark,
	FA_BOOK_SPARKLES_SOLID: fasBookSparkles,
	FA_BOX_ARCHIVE: faBoxArchive,
	FA_CALENDAR_DAYS: faCalendarDays,
	FA_CAMERA_SOLID: fasCamera,
	FA_CARET_SQUARE_RIGHT_SOLID: fasCaretSquareRight,
	FA_CART_SHOPPING: faCartShopping,
	FA_CHART_COLUMN: faChartColumn,
	FA_CHART_LINE_UP: faChartLineUp,
	FA_CHECK_SOLID: fasCheck,
	FA_CHEVRON_DOWN: faChevronDown,
	FA_CHEVRON_LEFT: faChevronLeft,
	FA_CHEVRON_LEFT_LIGHT: falChevronLeft,
	FA_CHEVRON_RIGHT: faChevronRight,
	FA_CHEVRON_RIGHT_LIGHT: falChevronRight,
	FA_CHEVRON_UP: faChevronUp,
	FA_CIRCLE: faCircle,
	FA_CIRCLE_ARROW_LEFT: faCircleArrowLeft,
	FA_CIRCLE_ARROW_RIGHT: faCircleArrowRight,
	FA_CIRCLE_CHECK: faCircleCheck,
	FA_CIRCLE_CHECK_SOLID: fasCircleCheck,
	FA_CIRCLE_ELLIPSIS: faCircleEllipsis,
	FA_CIRCLE_EXCLAMATION: faCircleExclamation,
	FA_CIRCLE_INFO: faCircleInfo,
	FA_CIRCLE_NOTCH: faCircleNotch,
	FA_CIRCLE_PLAY_SOLID: fasCirclePlay,
	FA_CIRCLE_QUESTION: faCircleQuestion,
	FA_CIRCLE_XMARK: faCircleXmark,
	FA_CLOCK: faClock,
	FA_CLOCK_ROTATE_LEFT: faClockRotateLeft,
	FA_CODE: faCode,
	FA_COMMENT: faComment,
	FA_COMMENTS: faComments,
	FA_COMMENT_DOTS: faCommentDots,
	FA_COMMENT_SOLID: fasComment,
	FA_COMPRESS: faCompress,
	FA_EARTH_AMERICAS: faEarthAmericas,
	FA_ELLIPSIS: faEllipsis,
	FA_ELLIPSIS_VERTICAL: faEllipsisVertical,
	FA_EXCLAMATION_SOLID: fasExclamation,
	FA_EYE: faEye,
	FA_EYE_SLASH: faEyeSlash,
	FA_FACEBOOK: faFacebook,
	FA_FACE_FROWN: faFaceFrown,
	FA_FACE_MEH: faFaceMeh,
	FA_FACE_SMILE: faFaceSmile,
	FA_FILE_INVOICE_DOLLAR: faFileInvoiceDollar,
	FA_FILE_LINES: faFileLines,
	FA_FILE_LINES_SOLID: fasFileLines,
	FA_FILE_PEN_SOLID: fasFilePen,
	FA_FILM: faFilm,
	FA_FILTER: faFilter,
	FA_FLAG: faFlag,
	FA_FLASK_SOLID: fasFlask,
	FA_FLOPPY_DISK: faFloppyDisk,
	FA_FOLDER_SOLID: fasFolder,
	FA_GAUGE_HIGH: faGaugeHigh,
	FA_GEAR: faGear,
	FA_GEARS_SOLID: fasGears,
	FA_GEAR_SOLID: fasGear,
	FA_GEM: faGem,
	FA_GIFT: faGift,
	FA_GRADUATION_CAP: faGraduationCap,
	FA_GRID: faGrid,
	FA_HANDS_SOLID: fasHands,
	FA_HAND_POINT_LEFT: faHandPointLeft,
	FA_HAND_SPOCK_SOLID: fasHandSpock,
	FA_HEART_PULSE: faHeartPulse,
	FA_HEART_SOLID: fasHeart,
	FA_HOURGLASS: faHourglass,
	FA_HOURGLASS_END: faHourglassEnd,
	FA_HOURGLASS_START: faHourglassStart,
	FA_HOUSE: faHouse,
	FA_INFO_SOLID: fasInfo,
	FA_KEY: faKey,
	FA_KEYBOARD: faKeyboard,
	FA_LIGHTBULB: faLightbulb,
	FA_LIGHTBULB_SOLID: fasLightbulb,
	FA_LINK: faLink,
	FA_LINK_SLASH: faLinkSlash,
	FA_LIST: faList,
	FA_LIST_CHECK: faListCheck,
	FA_LIST_OL: faListOl,
	FA_LOCATION_DOT: faLocationDot,
	FA_LOCK_KEYHOLE: faLockKeyhole,
	FA_MAGNIFYING_GLASS: faMagnifyingGlass,
	FA_MEDAL: faMedal,
	FA_MEMO_CIRCLE_INFO: faMemoCircleInfo,
	FA_MEMO_CIRCLE_INFO_SOLID: fasMemoCircleInfo,
	FA_MESSAGE_QUESTION_SOLID: fasMessageQuestion,
	FA_MINUS: faMinus,
	FA_MONEY_BILL1: faMoneyBill1,
	FA_MUSIC: faMusic,
	FA_PAPERCLIP: faPaperclip,
	FA_PAPER_PLANE: faPaperPlane,
	FA_PENCIL: faPencil,
	FA_PEN_CIRCLE: faPenCircle,
	FA_PEN_FIELD: faPenField,
	FA_PLAY: faPlay,
	FA_PLUS: faPlus,
	FA_PRINT: faPrint,
	FA_REPLY: faReply,
	FA_SHARE: faShare,
	FA_SHIELD_HALVED: faShieldHalved,
	FA_SIGNAL: faSignal,
	FA_SITEMAP: faSitemap,
	FA_SITEMAP_SOLID: fasSitemap,
	FA_SLIDERS: faSliders,
	FA_SPINNER_THIRD: faSpinnerThird,
	FA_SPELL_CHECK: faSpellCheck,
	FA_SQUARE: faSquare,
	FA_SQUARE_CARET_RIGHT: faSquareCaretRight,
	FA_SQUARE_CHECK: faSquareCheck,
	FA_SQUARE_LIST: faSquareList,
	FA_STAR: faStar,
	FA_STAR_SOLID: fasStar,
	FA_STOPWATCH_SOLID: fasStopwach,
	FA_TAG: faTag,
	FA_TAGS: faTags,
	FA_THUMBS_UP: faThumbsUp,
	FA_THUMBS_UP_SOLID: fasThumbsUp,
	FA_THUMBTACK_SOLID: fasThumbtack,
	FA_TRASH_CAN: faTrashCan,
	FA_TRIANGLE_EXCLAMATION: faTriangleExclamation,
	FA_TRIANGLE_EXCLAMATION_SOLID: fasTriangleExclamation,
	FA_TROPHY_STAR: faTrophyStar,
	FA_UNLOCK_KEYHOLE: faUnlockKeyhole,
	FA_UPLOAD: faUpload,
	FA_USER: faUser,
	FA_VIDEO_SOLID: fasVideo,
	FA_VOLUME_HIGH_SOLID: fasVolumeHigh,
	FA_WAND_MAGIC_SPARKLES: faWandMagicSparkles,
	FA_WINDOW_MAXIMIZE: faWindowMaximize,
	FA_XMARK: faXmark,
} as const;

export function initialize() {
	library.add(...Object.values(FONTAWESOME_ICONS));
}

export function initializeWithDomWatcher() {
	initialize();

	config.autoReplaceSvg = 'nest';
	dom.watch();
}

export { IconDefinition } from '@fortawesome/fontawesome-svg-core';
