import _paraguay from '../../../images/flags/001-paraguay.svg';
import _senegal from '../../../images/flags/002-senegal.svg';
import _democratic_republic_of_congo from '../../../images/flags/003-democratic republic of congo.svg';
import _estonia from '../../../images/flags/004-estonia.svg';
import _georgia from '../../../images/flags/005-georgia.svg';
import _ghana from '../../../images/flags/006-ghana.svg';
import _jersey from '../../../images/flags/007-jersey.svg';
import _madagascar from '../../../images/flags/008-madagascar.svg';
import _malawi from '../../../images/flags/009-malawi.svg';
import _mongolia from '../../../images/flags/010-mongolia.svg';
import _china from '../../../images/flags/011-china.svg';
import _nepal from '../../../images/flags/012-nepal.svg';
import _samoa from '../../../images/flags/013-samoa.svg';
import _haiti from '../../../images/flags/014-haiti.svg';
import _isle_of_man from '../../../images/flags/015-isle of man.svg';
import _ivory_coast from '../../../images/flags/016-ivory coast.svg';
import _lesotho from '../../../images/flags/017-lesotho.svg';
import _rwanda from '../../../images/flags/018-rwanda.svg';
import _zimbabwe from '../../../images/flags/019-zimbabwe.svg';
import _equatorial_guinea from '../../../images/flags/020-equatorial guinea.svg';
import _republic_of_the_congo from '../../../images/flags/021-republic of the congo.svg';
import _brazil from '../../../images/flags/022-brazil.svg';
import _sri_lanka from '../../../images/flags/023-sri lanka.svg';
import _swaziland from '../../../images/flags/024-swaziland.svg';
import _tajikistan from '../../../images/flags/025-tajikistan.svg';
import _trinidad_and_tobago from '../../../images/flags/026-trinidad and tobago.svg';
import _french_polynesia from '../../../images/flags/027-french polynesia.svg';
import _madeira from '../../../images/flags/028-madeira.svg';
import _maldives from '../../../images/flags/029-maldives.svg';
import _moldova from '../../../images/flags/030-moldova.svg';
import _montenegro from '../../../images/flags/031-montenegro.svg';
import _papua_new_guinea from '../../../images/flags/032-papua new guinea.svg';
import _mexico from '../../../images/flags/033-mexico.svg';
import _tibet from '../../../images/flags/034-tibet.svg';
import _east_timor from '../../../images/flags/035-East Timor.svg';
import _libya from '../../../images/flags/036-libya.svg';
import _otan from '../../../images/flags/037-otan.svg';
import _republic_of_macedonia from '../../../images/flags/038-republic of macedonia.svg';
import _sahrawi_arab_democratic_republic from '../../../images/flags/039-sahrawi arab democratic republic.svg';
import _sudan from '../../../images/flags/040-sudan.svg';
import _uzbekistan from '../../../images/flags/041-uzbekistan.svg';
import _yemen from '../../../images/flags/042-yemen.svg';
import _liberia from '../../../images/flags/043-liberia.svg';
import _russia from '../../../images/flags/044-russia.svg';
import _liechtenstein from '../../../images/flags/045-liechtenstein.svg';
import _northen_cyprus from '../../../images/flags/046-northen cyprus.svg';
import _san_marino from '../../../images/flags/047-san marino.svg';
import _st_barts from '../../../images/flags/048-st barts.svg';
import _curacao from '../../../images/flags/049-curacao.svg';
import _djibouti from '../../../images/flags/050-djibouti.svg';
import _eritrea from '../../../images/flags/051-eritrea.svg';
import _guinea_bissau from '../../../images/flags/052-guinea bissau.svg';
import _kyrgyzstan from '../../../images/flags/053-kyrgyzstan.svg';
import _mali from '../../../images/flags/054-mali.svg';
import _india from '../../../images/flags/055-india.svg';
import _marshall_island from '../../../images/flags/056-marshall island.svg';
import _micronesia from '../../../images/flags/057-micronesia.svg';
import _niger from '../../../images/flags/058-niger.svg';
import _norfolk_island from '../../../images/flags/059-norfolk island.svg';
import _sao_tome_and_principe from '../../../images/flags/060-sao tome and principe.svg';
import _sardinia from '../../../images/flags/061-sardinia.svg';
import _sicily from '../../../images/flags/062-Sicily.svg';
import _somalia from '../../../images/flags/063-somalia.svg';
import _suriname from '../../../images/flags/064-suriname.svg';
import _azores_islands from '../../../images/flags/065-azores islands.svg';
import _canada from '../../../images/flags/066-canada.svg';
import _bahamas from '../../../images/flags/067-bahamas.svg';
import _togo from '../../../images/flags/068-togo.svg';
import _turkmenistan from '../../../images/flags/069-turkmenistan.svg';
import _tubalu from '../../../images/flags/070-tubalu.svg';
import _vatican_city from '../../../images/flags/071-vatican city.svg';
import _austria from '../../../images/flags/072-austria.svg';
import _virgin_islands from '../../../images/flags/073-virgin islands.svg';
import _falkland_islands from '../../../images/flags/074-falkland islands.svg';
import _gabon from '../../../images/flags/075-gabon.svg';
import _gibraltar from '../../../images/flags/076-gibraltar.svg';
import _netherlands from '../../../images/flags/077-netherlands.svg';
import _greenland from '../../../images/flags/078-greenland.svg';
import _grenada from '../../../images/flags/079-grenada.svg';
import _guam from '../../../images/flags/080-guam.svg';
import _guernsey from '../../../images/flags/081-guernsey.svg';
import _kiribati from '../../../images/flags/082-kiribati.svg';
import _kuwait from '../../../images/flags/083-kuwait.svg';
import _mauritania from '../../../images/flags/084-mauritania.svg';
import _melilla from '../../../images/flags/085-melilla.svg';
import _montserrat from '../../../images/flags/086-montserrat.svg';
import _thailand from '../../../images/flags/087-thailand.svg';
import _nauru from '../../../images/flags/088-nauru.svg';
import _northern_marianas_islands from '../../../images/flags/089-northern marianas islands.svg';
import _ossetia from '../../../images/flags/090-ossetia.svg';
import _palestine from '../../../images/flags/091-palestine.svg';
import _pitcairn_islands from '../../../images/flags/092-pitcairn islands.svg';
import _saba_island from '../../../images/flags/093-saba island.svg';
import _saint_kitts_and_nevis from '../../../images/flags/094-saint kitts and nevis.svg';
import _sint_eustatius from '../../../images/flags/095-sint eustatius.svg';
import _sint_maarten from '../../../images/flags/096-sint maarten.svg';
import _portugal from '../../../images/flags/097-portugal.svg';
import _solomon_islands from '../../../images/flags/098-solomon islands.svg';
import _somaliland from '../../../images/flags/099-somaliland.svg';
import _south_sudan from '../../../images/flags/100-south sudan.svg';
import _st_vincent_and_the_grenadines from '../../../images/flags/101-st vincent and the grenadines.svg';
import _gambia from '../../../images/flags/102-gambia.svg';
import _tokelau from '../../../images/flags/103-tokelau.svg';
import _transnistria from '../../../images/flags/104-transnistria.svg';
import _turks_and_caicos from '../../../images/flags/105-turks and caicos.svg';
import _orkney_islands from '../../../images/flags/106-orkney islands.svg';
import _guinea from '../../../images/flags/107-guinea.svg';
import _vietnam from '../../../images/flags/108-vietnam.svg';
import _united_kingdom from '../../../images/flags/109-united kingdom.svg';
import _kosovo from '../../../images/flags/110-kosovo.svg';
import _seychelles from '../../../images/flags/111-seychelles.svg';
import _sierra_leone from '../../../images/flags/112-sierra leone.svg';
import _vanuatu from '../../../images/flags/113-vanuatu.svg';
import _dominica from '../../../images/flags/114-dominica.svg';
import _faroe_islands from '../../../images/flags/115-faroe islands.svg';
import _fiji from '../../../images/flags/116-fiji.svg';
import _macao from '../../../images/flags/117-macao.svg';
import _niue from '../../../images/flags/118-niue.svg';
import _palau from '../../../images/flags/119-palau.svg';
import _england from '../../../images/flags/120-england.svg';
import _rapa_nui from '../../../images/flags/121-Rapa Nui.svg';
import _st_lucia from '../../../images/flags/122-st lucia.svg';
import _tonga from '../../../images/flags/123-tonga.svg';
import _martinique from '../../../images/flags/124-martinique.svg';
import _galapagos_islands from '../../../images/flags/125-galapagos islands.svg';
import _bulgaria from '../../../images/flags/126-bulgaria.svg';
import _croatia from '../../../images/flags/127-croatia.svg';
import _bolivia from '../../../images/flags/128-bolivia.svg';
import _cambodia from '../../../images/flags/129-cambodia.svg';
import _costa_rica from '../../../images/flags/130-costa rica.svg';
import _singapore from '../../../images/flags/131-singapore.svg';
import _cuba from '../../../images/flags/132-cuba.svg';
import _bangladesh from '../../../images/flags/133-bangladesh.svg';
import _botswana from '../../../images/flags/134-botswana.svg';
import _algeria from '../../../images/flags/135-Algeria.svg';
import _azerbaijan from '../../../images/flags/136-azerbaijan.svg';
import _angola from '../../../images/flags/137-angola.svg';
import _british_columbia from '../../../images/flags/138-british columbia.svg';
import _afghanistan from '../../../images/flags/139-afghanistan.svg';
import _armenia from '../../../images/flags/140-armenia.svg';
import _basque_country from '../../../images/flags/141-basque country.svg';
import _australia from '../../../images/flags/142-australia.svg';
import _burkina_faso from '../../../images/flags/143-burkina faso.svg';
import _albania from '../../../images/flags/144-albania.svg';
import _bahrain from '../../../images/flags/145-bahrain.svg';
import _belize from '../../../images/flags/146-belize.svg';
import _bermuda from '../../../images/flags/147-bermuda.svg';
import _bosnia_and_herzegovina from '../../../images/flags/148-bosnia and herzegovina.svg';
import _british_virgin_islands from '../../../images/flags/149-british virgin islands.svg';
import _barbados from '../../../images/flags/150-barbados.svg';
import _belarus from '../../../images/flags/151-belarus.svg';
import _bonaire from '../../../images/flags/152-bonaire.svg';
import _turkey from '../../../images/flags/153-turkey.svg';
import _brunei from '../../../images/flags/154-brunei.svg';
import _cameroon from '../../../images/flags/155-cameroon.svg';
import _aland_islands from '../../../images/flags/156-aland islands.svg';
import _antigua_and_barbuda from '../../../images/flags/157-antigua and barbuda.svg';
import _burundi from '../../../images/flags/158-burundi.svg';
import _andorra from '../../../images/flags/159-andorra.svg';
import _balearic_islands from '../../../images/flags/160-balearic islands.svg';
import _abkhazia from '../../../images/flags/161-abkhazia.svg';
import _aruba from '../../../images/flags/162-aruba.svg';
import _benin from '../../../images/flags/163-benin.svg';
import _poland from '../../../images/flags/164-poland.svg';
import _cape_verde from '../../../images/flags/165-cape verde.svg';
import _chad from '../../../images/flags/166-chad.svg';
import _bhutan from '../../../images/flags/167-bhutan.svg';
import _british_indian_ocean_territory from '../../../images/flags/168-british indian ocean territory.svg';
import _cayman_islands from '../../../images/flags/169-cayman islands.svg';
import _central_african_republic from '../../../images/flags/170-central african republic.svg';
import _comoros from '../../../images/flags/171-comoros.svg';
import _canary_islands from '../../../images/flags/172-canary islands.svg';
import _corsica from '../../../images/flags/173-corsica.svg';
import _anguilla from '../../../images/flags/174-anguilla.svg';
import _switzerland from '../../../images/flags/175-switzerland.svg';
import _american_samoa from '../../../images/flags/176-american samoa.svg';
import _ceuta from '../../../images/flags/177-ceuta.svg';
import _christmas_island from '../../../images/flags/178-christmas island.svg';
import _cocos_island from '../../../images/flags/179-cocos island.svg';
import _cook_islands from '../../../images/flags/180-cook islands.svg';
import _morocco from '../../../images/flags/181-morocco.svg';
import _taiwan from '../../../images/flags/182-taiwan.svg';
import _egypt from '../../../images/flags/183-egypt.svg';
import _indonesia from '../../../images/flags/184-indonesia.svg';
import _united_states_of_america from '../../../images/flags/185-united states of america.svg';
import _philippines from '../../../images/flags/186-philippines.svg';
import _south_africa from '../../../images/flags/187-south africa.svg';
import _peru from '../../../images/flags/188-peru.svg';
import _sweden from '../../../images/flags/189-sweden.svg';
import _denmark from '../../../images/flags/190-denmark.svg';
import _greece from '../../../images/flags/191-greece.svg';
import _ireland from '../../../images/flags/192-ireland.svg';
import _laos from '../../../images/flags/193-laos.svg';
import _united_arab_emirates from '../../../images/flags/194-united arab emirates.svg';
import _hong_kong from '../../../images/flags/195-hong kong.svg';
import _france from '../../../images/flags/196-france.svg';
import _ukraine from '../../../images/flags/197-ukraine.svg';
import _argentina from '../../../images/flags/198-argentina.svg';
import _iran from '../../../images/flags/199-iran.svg';
import _colombia from '../../../images/flags/200-colombia.svg';
import _czech_republic from '../../../images/flags/201-czech republic.svg';
import _israel from '../../../images/flags/202-israel.svg';
import _saudi_arabia from '../../../images/flags/203-saudi arabia.svg';
import _norway from '../../../images/flags/204-norway.svg';
import _venezuela from '../../../images/flags/205-venezuela.svg';
import _malaysia from '../../../images/flags/206-malaysia.svg';
import _germany from '../../../images/flags/207-germany.svg';
import _belgium from '../../../images/flags/208-belgium.svg';
import _hungary from '../../../images/flags/209-hungary.svg';
import _finland from '../../../images/flags/210-finland.svg';
import _chile from '../../../images/flags/211-chile.svg';
import _romania from '../../../images/flags/212-romania.svg';
import _ecuador from '../../../images/flags/213-ecuador.svg';
import _new_zealand from '../../../images/flags/214-new zealand.svg';
import _panama from '../../../images/flags/215-panama.svg';
import _united_nations from '../../../images/flags/216-united nations.svg';
import _slovakia from '../../../images/flags/217-slovakia.svg';
import _south_korea from '../../../images/flags/218-south korea.svg';
import _monaco from '../../../images/flags/219-monaco.svg';
import _jordan from '../../../images/flags/220-jordan.svg';
import _iceland from '../../../images/flags/221-iceland.svg';
import _guatemala from '../../../images/flags/222-guatemala.svg';
import _syria from '../../../images/flags/223-syria.svg';
import _uruguay from '../../../images/flags/224-uruguay.svg';
import _north_korea from '../../../images/flags/225-north korea.svg';
import _scotland from '../../../images/flags/226-scotland.svg';
import _serbia from '../../../images/flags/227-serbia.svg';
import _kazakhstan from '../../../images/flags/228-kazakhstan.svg';
import _spain from '../../../images/flags/229-spain.svg';
import _latvia from '../../../images/flags/230-latvia.svg';
import _pakistan from '../../../images/flags/231-pakistan.svg';
import _cyprus from '../../../images/flags/232-cyprus.svg';
import _kenya from '../../../images/flags/233-kenya.svg';
import _myanmar from '../../../images/flags/234-myanmar.svg';
import _honduras from '../../../images/flags/235-honduras.svg';
import _jamaica from '../../../images/flags/236-jamaica.svg';
import _lithuania from '../../../images/flags/237-lithuania.svg';
import _hawaii from '../../../images/flags/238-hawaii.svg';
import _luxembourg from '../../../images/flags/239-luxembourg.svg';
import _japan from '../../../images/flags/240-japan.svg';
import _mauritius from '../../../images/flags/241-mauritius.svg';
import _namibia from '../../../images/flags/242-namibia.svg';
import _qatar from '../../../images/flags/243-qatar.svg';
import _dominican_republic from '../../../images/flags/244-dominican republic.svg';
import _wales from '../../../images/flags/245-wales.svg';
import _zambia from '../../../images/flags/246-zambia.svg';
import _el_salvador from '../../../images/flags/247-el salvador.svg';
import _nicaragua from '../../../images/flags/248-nicaragua.svg';
import _tunisia from '../../../images/flags/249-tunisia.svg';
import _malta from '../../../images/flags/250-malta.svg';
import _european_union from '../../../images/flags/251-european union.svg';
import _nigeria from '../../../images/flags/252-nigeria.svg';
import _uganda from '../../../images/flags/253-uganda.svg';
import _lebanon from '../../../images/flags/254-lebanon.svg';
import _iraq from '../../../images/flags/255-iraq.svg';
import _mozambique from '../../../images/flags/256-mozambique.svg';
import _puerto_rico from '../../../images/flags/257-puerto rico.svg';
import _slovenia from '../../../images/flags/258-slovenia.svg';
import _tanzania from '../../../images/flags/259-tanzania.svg';
import _oman from '../../../images/flags/260-oman.svg';
import _ethiopia from '../../../images/flags/261-ethiopia.svg';
import _italy from '../../../images/flags/262-italy.svg';

export const FLAG_PARAGUAY = _paraguay;
export const FLAG_SENEGAL = _senegal;
export const FLAG_DEMOCRATIC_REPUBLIC_OF_CONGO = _democratic_republic_of_congo;
export const FLAG_ESTONIA = _estonia;
export const FLAG_GEORGIA = _georgia;
export const FLAG_GHANA = _ghana;
export const FLAG_JERSEY = _jersey;
export const FLAG_MADAGASCAR = _madagascar;
export const FLAG_MALAWI = _malawi;
export const FLAG_MONGOLIA = _mongolia;
export const FLAG_CHINA = _china;
export const FLAG_NEPAL = _nepal;
export const FLAG_SAMOA = _samoa;
export const FLAG_HAITI = _haiti;
export const FLAG_ISLE_OF_MAN = _isle_of_man;
export const FLAG_IVORY_COAST = _ivory_coast;
export const FLAG_LESOTHO = _lesotho;
export const FLAG_RWANDA = _rwanda;
export const FLAG_ZIMBABWE = _zimbabwe;
export const FLAG_EQUATORIAL_GUINEA = _equatorial_guinea;
export const FLAG_REPUBLIC_OF_THE_CONGO = _republic_of_the_congo;
export const FLAG_BRAZIL = _brazil;
export const FLAG_SRI_LANKA = _sri_lanka;
export const FLAG_SWAZILAND = _swaziland;
export const FLAG_TAJIKISTAN = _tajikistan;
export const FLAG_TRINIDAD_AND_TOBAGO = _trinidad_and_tobago;
export const FLAG_FRENCH_POLYNESIA = _french_polynesia;
export const FLAG_MADEIRA = _madeira;
export const FLAG_MALDIVES = _maldives;
export const FLAG_MOLDOVA = _moldova;
export const FLAG_MONTENEGRO = _montenegro;
export const FLAG_PAPUA_NEW_GUINEA = _papua_new_guinea;
export const FLAG_MEXICO = _mexico;
export const FLAG_TIBET = _tibet;
export const FLAG_EAST_TIMOR = _east_timor;
export const FLAG_LIBYA = _libya;
export const FLAG_OTAN = _otan;
export const FLAG_REPUBLIC_OF_MACEDONIA = _republic_of_macedonia;
export const FLAG_SAHRAWI_ARAB_DEMOCRATIC_REPUBLIC = _sahrawi_arab_democratic_republic;
export const FLAG_SUDAN = _sudan;
export const FLAG_UZBEKISTAN = _uzbekistan;
export const FLAG_YEMEN = _yemen;
export const FLAG_LIBERIA = _liberia;
export const FLAG_RUSSIA = _russia;
export const FLAG_LIECHTENSTEIN = _liechtenstein;
export const FLAG_NORTHEN_CYPRUS = _northen_cyprus;
export const FLAG_SAN_MARINO = _san_marino;
export const FLAG_ST_BARTS = _st_barts;
export const FLAG_CURACAO = _curacao;
export const FLAG_DJIBOUTI = _djibouti;
export const FLAG_ERITREA = _eritrea;
export const FLAG_GUINEA_BISSAU = _guinea_bissau;
export const FLAG_KYRGYZSTAN = _kyrgyzstan;
export const FLAG_MALI = _mali;
export const FLAG_INDIA = _india;
export const FLAG_MARSHALL_ISLAND = _marshall_island;
export const FLAG_MICRONESIA = _micronesia;
export const FLAG_NIGER = _niger;
export const FLAG_NORFOLK_ISLAND = _norfolk_island;
export const FLAG_SAO_TOME_AND_PRINCIPE = _sao_tome_and_principe;
export const FLAG_SARDINIA = _sardinia;
export const FLAG_SICILY = _sicily;
export const FLAG_SOMALIA = _somalia;
export const FLAG_SURINAME = _suriname;
export const FLAG_AZORES_ISLANDS = _azores_islands;
export const FLAG_CANADA = _canada;
export const FLAG_BAHAMAS = _bahamas;
export const FLAG_TOGO = _togo;
export const FLAG_TURKMENISTAN = _turkmenistan;
export const FLAG_TUBALU = _tubalu;
export const FLAG_VATICAN_CITY = _vatican_city;
export const FLAG_AUSTRIA = _austria;
export const FLAG_VIRGIN_ISLANDS = _virgin_islands;
export const FLAG_FALKLAND_ISLANDS = _falkland_islands;
export const FLAG_GABON = _gabon;
export const FLAG_GIBRALTAR = _gibraltar;
export const FLAG_NETHERLANDS = _netherlands;
export const FLAG_GREENLAND = _greenland;
export const FLAG_GRENADA = _grenada;
export const FLAG_GUAM = _guam;
export const FLAG_GUERNSEY = _guernsey;
export const FLAG_KIRIBATI = _kiribati;
export const FLAG_KUWAIT = _kuwait;
export const FLAG_MAURITANIA = _mauritania;
export const FLAG_MELILLA = _melilla;
export const FLAG_MONTSERRAT = _montserrat;
export const FLAG_THAILAND = _thailand;
export const FLAG_NAURU = _nauru;
export const FLAG_NORTHERN_MARIANAS_ISLANDS = _northern_marianas_islands;
export const FLAG_OSSETIA = _ossetia;
export const FLAG_PALESTINE = _palestine;
export const FLAG_PITCAIRN_ISLANDS = _pitcairn_islands;
export const FLAG_SABA_ISLAND = _saba_island;
export const FLAG_SAINT_KITTS_AND_NEVIS = _saint_kitts_and_nevis;
export const FLAG_SINT_EUSTATIUS = _sint_eustatius;
export const FLAG_SINT_MAARTEN = _sint_maarten;
export const FLAG_PORTUGAL = _portugal;
export const FLAG_SOLOMON_ISLANDS = _solomon_islands;
export const FLAG_SOMALILAND = _somaliland;
export const FLAG_SOUTH_SUDAN = _south_sudan;
export const FLAG_ST_VINCENT_AND_THE_GRENADINES = _st_vincent_and_the_grenadines;
export const FLAG_GAMBIA = _gambia;
export const FLAG_TOKELAU = _tokelau;
export const FLAG_TRANSNISTRIA = _transnistria;
export const FLAG_TURKS_AND_CAICOS = _turks_and_caicos;
export const FLAG_ORKNEY_ISLANDS = _orkney_islands;
export const FLAG_GUINEA = _guinea;
export const FLAG_VIETNAM = _vietnam;
export const FLAG_UNITED_KINGDOM = _united_kingdom;
export const FLAG_KOSOVO = _kosovo;
export const FLAG_SEYCHELLES = _seychelles;
export const FLAG_SIERRA_LEONE = _sierra_leone;
export const FLAG_VANUATU = _vanuatu;
export const FLAG_DOMINICA = _dominica;
export const FLAG_FAROE_ISLANDS = _faroe_islands;
export const FLAG_FIJI = _fiji;
export const FLAG_MACAO = _macao;
export const FLAG_NIUE = _niue;
export const FLAG_PALAU = _palau;
export const FLAG_ENGLAND = _england;
export const FLAG_RAPA_NUI = _rapa_nui;
export const FLAG_ST_LUCIA = _st_lucia;
export const FLAG_TONGA = _tonga;
export const FLAG_MARTINIQUE = _martinique;
export const FLAG_GALAPAGOS_ISLANDS = _galapagos_islands;
export const FLAG_BULGARIA = _bulgaria;
export const FLAG_CROATIA = _croatia;
export const FLAG_BOLIVIA = _bolivia;
export const FLAG_CAMBODIA = _cambodia;
export const FLAG_COSTA_RICA = _costa_rica;
export const FLAG_SINGAPORE = _singapore;
export const FLAG_CUBA = _cuba;
export const FLAG_BANGLADESH = _bangladesh;
export const FLAG_BOTSWANA = _botswana;
export const FLAG_ALGERIA = _algeria;
export const FLAG_AZERBAIJAN = _azerbaijan;
export const FLAG_ANGOLA = _angola;
export const FLAG_BRITISH_COLUMBIA = _british_columbia;
export const FLAG_AFGHANISTAN = _afghanistan;
export const FLAG_ARMENIA = _armenia;
export const FLAG_BASQUE_COUNTRY = _basque_country;
export const FLAG_AUSTRALIA = _australia;
export const FLAG_BURKINA_FASO = _burkina_faso;
export const FLAG_ALBANIA = _albania;
export const FLAG_BAHRAIN = _bahrain;
export const FLAG_BELIZE = _belize;
export const FLAG_BERMUDA = _bermuda;
export const FLAG_BOSNIA_AND_HERZEGOVINA = _bosnia_and_herzegovina;
export const FLAG_BRITISH_VIRGIN_ISLANDS = _british_virgin_islands;
export const FLAG_BARBADOS = _barbados;
export const FLAG_BELARUS = _belarus;
export const FLAG_BONAIRE = _bonaire;
export const FLAG_TURKEY = _turkey;
export const FLAG_BRUNEI = _brunei;
export const FLAG_CAMEROON = _cameroon;
export const FLAG_ALAND_ISLANDS = _aland_islands;
export const FLAG_ANTIGUA_AND_BARBUDA = _antigua_and_barbuda;
export const FLAG_BURUNDI = _burundi;
export const FLAG_ANDORRA = _andorra;
export const FLAG_BALEARIC_ISLANDS = _balearic_islands;
export const FLAG_ABKHAZIA = _abkhazia;
export const FLAG_ARUBA = _aruba;
export const FLAG_BENIN = _benin;
export const FLAG_POLAND = _poland;
export const FLAG_CAPE_VERDE = _cape_verde;
export const FLAG_CHAD = _chad;
export const FLAG_BHUTAN = _bhutan;
export const FLAG_BRITISH_INDIAN_OCEAN_TERRITORY = _british_indian_ocean_territory;
export const FLAG_CAYMAN_ISLANDS = _cayman_islands;
export const FLAG_CENTRAL_AFRICAN_REPUBLIC = _central_african_republic;
export const FLAG_COMOROS = _comoros;
export const FLAG_CANARY_ISLANDS = _canary_islands;
export const FLAG_CORSICA = _corsica;
export const FLAG_ANGUILLA = _anguilla;
export const FLAG_SWITZERLAND = _switzerland;
export const FLAG_AMERICAN_SAMOA = _american_samoa;
export const FLAG_CEUTA = _ceuta;
export const FLAG_CHRISTMAS_ISLAND = _christmas_island;
export const FLAG_COCOS_ISLAND = _cocos_island;
export const FLAG_COOK_ISLANDS = _cook_islands;
export const FLAG_MOROCCO = _morocco;
export const FLAG_TAIWAN = _taiwan;
export const FLAG_EGYPT = _egypt;
export const FLAG_INDONESIA = _indonesia;
export const FLAG_UNITED_STATES_OF_AMERICA = _united_states_of_america;
export const FLAG_PHILIPPINES = _philippines;
export const FLAG_SOUTH_AFRICA = _south_africa;
export const FLAG_PERU = _peru;
export const FLAG_SWEDEN = _sweden;
export const FLAG_DENMARK = _denmark;
export const FLAG_GREECE = _greece;
export const FLAG_IRELAND = _ireland;
export const FLAG_LAOS = _laos;
export const FLAG_UNITED_ARAB_EMIRATES = _united_arab_emirates;
export const FLAG_HONG_KONG = _hong_kong;
export const FLAG_FRANCE = _france;
export const FLAG_UKRAINE = _ukraine;
export const FLAG_ARGENTINA = _argentina;
export const FLAG_IRAN = _iran;
export const FLAG_COLOMBIA = _colombia;
export const FLAG_CZECH_REPUBLIC = _czech_republic;
export const FLAG_ISRAEL = _israel;
export const FLAG_SAUDI_ARABIA = _saudi_arabia;
export const FLAG_NORWAY = _norway;
export const FLAG_VENEZUELA = _venezuela;
export const FLAG_MALAYSIA = _malaysia;
export const FLAG_GERMANY = _germany;
export const FLAG_BELGIUM = _belgium;
export const FLAG_HUNGARY = _hungary;
export const FLAG_FINLAND = _finland;
export const FLAG_CHILE = _chile;
export const FLAG_ROMANIA = _romania;
export const FLAG_ECUADOR = _ecuador;
export const FLAG_NEW_ZEALAND = _new_zealand;
export const FLAG_PANAMA = _panama;
export const FLAG_UNITED_NATIONS = _united_nations;
export const FLAG_SLOVAKIA = _slovakia;
export const FLAG_SOUTH_KOREA = _south_korea;
export const FLAG_MONACO = _monaco;
export const FLAG_JORDAN = _jordan;
export const FLAG_ICELAND = _iceland;
export const FLAG_GUATEMALA = _guatemala;
export const FLAG_SYRIA = _syria;
export const FLAG_URUGUAY = _uruguay;
export const FLAG_NORTH_KOREA = _north_korea;
export const FLAG_SCOTLAND = _scotland;
export const FLAG_SERBIA = _serbia;
export const FLAG_KAZAKHSTAN = _kazakhstan;
export const FLAG_SPAIN = _spain;
export const FLAG_LATVIA = _latvia;
export const FLAG_PAKISTAN = _pakistan;
export const FLAG_CYPRUS = _cyprus;
export const FLAG_KENYA = _kenya;
export const FLAG_MYANMAR = _myanmar;
export const FLAG_HONDURAS = _honduras;
export const FLAG_JAMAICA = _jamaica;
export const FLAG_LITHUANIA = _lithuania;
export const FLAG_HAWAII = _hawaii;
export const FLAG_LUXEMBOURG = _luxembourg;
export const FLAG_JAPAN = _japan;
export const FLAG_MAURITIUS = _mauritius;
export const FLAG_NAMIBIA = _namibia;
export const FLAG_QATAR = _qatar;
export const FLAG_DOMINICAN_REPUBLIC = _dominican_republic;
export const FLAG_WALES = _wales;
export const FLAG_ZAMBIA = _zambia;
export const FLAG_EL_SALVADOR = _el_salvador;
export const FLAG_NICARAGUA = _nicaragua;
export const FLAG_TUNISIA = _tunisia;
export const FLAG_MALTA = _malta;
export const FLAG_EUROPEAN_UNION = _european_union;
export const FLAG_NIGERIA = _nigeria;
export const FLAG_UGANDA = _uganda;
export const FLAG_LEBANON = _lebanon;
export const FLAG_IRAQ = _iraq;
export const FLAG_MOZAMBIQUE = _mozambique;
export const FLAG_PUERTO_RICO = _puerto_rico;
export const FLAG_SLOVENIA = _slovenia;
export const FLAG_TANZANIA = _tanzania;
export const FLAG_OMAN = _oman;
export const FLAG_ETHIOPIA = _ethiopia;
export const FLAG_ITALY = _italy;
