export const COLORS = {
	PRIMARY: '#0f9698',
	PRIMARY_SUPPORTING: '#87cacb',
	PRIMARY_BACKGROUND: '#d8eeee',

	SECONDARY: '#11afb2',
	SECONDARY_SUPPORTING: '#8ececf',

	JUNGLE_GREEN: '#27AA5B',
	ELF_GREEN: '#239952',
	SALAD_GREEN: '#4AB24F',
	ICE_GREEN: '#E2F2E3',
	GARDEN_GREEN: '#98D293',
	MANTIS_GREEN: '#8BC34A',
	WASABI_GREEN: '#AED581',

	CRIMSON_RED: '#DE2F1B',
	FRENCH_RED: '#E55066',
	BRUSH_RED: '#EE978D',

	COBALT_BLUE: '#2F4999',
	NAVY_BLUE: '#0277BD',
	BABY_BLUE: '#81D4FA',

	POWDER_PINK: '#FADEDA',

	ICE_YELLOW: '#FEF3DD',
	LEMON_YELLOW: '#FFF176',
	GORSE_YELLOW: '#FDD835',
	MUSTARD_YELLOW: '#FFD54F',
	AMBER_YELLOW: '#FFC107',
	GOLDFISH_YELLOW: '#FDB72D',
	CALIFORNIA_YELLOW: '#ECA005',
	MELON_ORANGE: '#FF8A65',
	OUTRAGEOUS_ORANGE: '#FF5722',
	SATIN_ORANGE: '#cc3e17',

	GIGAS_VIOLET: '#62378D',
	DELUGE_VIOLET: '#7B569F',

	ICE_ORANGE: '#FFE6CA',

	FIREFLY_BLACK: '#0C1726',
	CATALINA_BLUE: '#25335A',
	RHINO_GRAY: '#434A5A',
	STORM_GRAY: '#6F7285',
	CADET_GRAY: '#A7ACBD',
	MISCHKA_GRAY: '#CDD0DA',
	ATHENS_GRAY: '#E6E8EE',
	ALABASTER_GRAY: '#F6F6F8',
	TOTAL_WHITE: '#FFFFFF',
};

export const THEME_COLORS = {
	PRIMARY: COLORS.PRIMARY,
	PRIMARY_SUPPORTING: COLORS.PRIMARY_SUPPORTING,
	PRIMARY_BACKGROUND: COLORS.PRIMARY_BACKGROUND,
	SECONDARY: COLORS.SECONDARY,
	SECONDARY_SUPPORTING: COLORS.SECONDARY_SUPPORTING,
	CONTENT: COLORS.FIREFLY_BLACK,
	CONTENT_INVERTED: COLORS.TOTAL_WHITE,
	BACKGROUND: COLORS.TOTAL_WHITE,
	BACKGROUND_SECONDARY: COLORS.ALABASTER_GRAY,
};

export const FUNCTIONAL_COLORS = {
	SUCCESS: COLORS.SALAD_GREEN,
	SUCCESS_SUPPORTING: COLORS.GARDEN_GREEN,
	SUCCESS_BACKGROUND: COLORS.ICE_GREEN,

	WARNING: COLORS.GOLDFISH_YELLOW,
	WARNING_SUPPORTING: COLORS.MUSTARD_YELLOW,
	WARNING_BACKGROUND: COLORS.ICE_YELLOW,

	DANGER: COLORS.CRIMSON_RED,
	DANGER_SUPPORTING: COLORS.BRUSH_RED,
	DANGER_BACKGROUND: COLORS.POWDER_PINK,

	MINOR: COLORS.STORM_GRAY,
	MINOR_SUPPORTING: COLORS.CADET_GRAY,
	MINOR_BACKGROUND: COLORS.ATHENS_GRAY,

	FAIL: COLORS.OUTRAGEOUS_ORANGE,
	FAIL_SUPPORTING: COLORS.MELON_ORANGE,
	FAIL_BACKGROUND: COLORS.ICE_ORANGE,
};
