export const COLORS = {
	PRIMARY: '#0f9698',
	PRIMARY_SUPPORTING: '#87cacb',
	SECONDARY: '#11afb2',
	SECONDARY_SUPPORTING: '#8ececf',

	JUNGLE_GREEN: '#27AA5B',
	ELF_GREEN: '#239952',
	SALAD_GREEN: '#43A047',
	OCEAN_GREEN: '#44B490',
	GARDEN_GREEN: '#81C784',
	MANTIS_GREEN: '#8BC34A',
	WASABI_GREEN: '#AED581',

	CRIMSON_RED: '#DE2F1B',
	FRENCH_RED: '#E55066',
	CRIMSON_RED_LIGHT: '#EE978D',

	COBALT_BLUE: '#2F4999',
	NAVY_BLUE: '#0277BD',
	OPAL_BLUE: '#87CACB',
	BABY_BLUE: '#81D4FA',

	LEMON_YELLOW: '#FFF176',
	GORSE_YELLOW: '#FDD835',
	MUSTARD_YELLOW: '#FFD54F',
	AMBER_YELLOW: '#FFC107',
	GOLDFISH_YELLOW: '#FDB72D',
	CALIFORNIA_YELLOW: '#ECA005',
	MELON_ORANGE: '#FF8A65',
	OUTRAGEOUS_ORANGE: '#FF5722',
	SATIN_ORANGE: '#cc3e17',

	GIGAS_VIOLET: '#62378D',
	DELUGE_VIOLET: '#7B569F',

	FIREFLY_BLACK: '#0C1726',
	CATALINA_BLUE: '#25335A',
	RHINO_GRAY: '#434A5A',
	STORM_GRAY: '#6F7285',
	CADET_GRAY: '#A7ACBD',
	MISCHKA_GRAY: '#CDD0DA',
	ATHENS_GRAY: '#E6E8EE',
	ALABASTER_GRAY: '#F6F6F8',
	TOTAL_WHITE: '#FFFFFF',
};

export const THEME_COLORS = {
	PRIMARY: COLORS.PRIMARY,
	PRIMARY_SUPPORTING: COLORS.PRIMARY_SUPPORTING,
	SECONDARY: COLORS.SECONDARY,
	SECONDARY_SUPPORTING: COLORS.SECONDARY_SUPPORTING,
	CONTENT: COLORS.FIREFLY_BLACK,
	CONTENT_INVERTED: COLORS.TOTAL_WHITE,
	BACKGROUND: COLORS.TOTAL_WHITE,
	BACKGROUND_SECONDARY: COLORS.ALABASTER_GRAY,
};

export const FUNCTIONAL_COLORS = {
	SUCCESS: COLORS.OCEAN_GREEN,
	WARNING: COLORS.GOLDFISH_YELLOW,
	DANGER: COLORS.CRIMSON_RED,
	DANGER_SUPPORTING: COLORS.CRIMSON_RED_LIGHT,
	MINOR: COLORS.STORM_GRAY,
	MINOR_SUPPORTING: COLORS.CADET_GRAY,
};
